### PR TITLE
Minor typo fixes

### PR DESCRIPTION
**Pull request by Zorlin**
Corrects some language/grammar/typos.

### CODE REVIEW

**Comment by immarvin** [comment]
i am ok with the change, thanks @Zorlin

**Comment by Zorlin** [comment]
Awesome, thanks :)

**Comment by immarvin** [comment]
@Zorlin , thanks for your contribution. Are you already using `xcat-inventory`?

**Comment by Zorlin** [comment]
@immarvin Not yet. We're using an older version of xCAT and looking forward to trying xcat-inventory as part of our upgrades :)

**Pull request merged**
