### PR TITLE
Fix #221: RHEL8 compatibility + v0.1.7

### LINKED ISSUE #221: xcat-inventory failed to install on rhels8.1
Current xcat-inventory only supports python2.  On rhels8.1, python3 is supported.  the xcat-inventory depends packages are different on the python3 environment.
```
 # wget https://github.com/xcat2/xcat-inventory/releases/download/v0.1.6/xcat-inventory-0.1.6-c0.noarch.rpm
# # yum install ./xcat-inventory-0.1.6-c0.noarch.rpm
Updating Subscription Management repositories.
Unable to read consumer identity
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Last metadata expiration check: 0:53:51 ago on Fri 21 Feb 2020 02:39:49 PM EST.
Error:
 Problem: conflicting requests
  - nothing provides python-sqlalchemy >= 0.8.0 needed by xcat-inventory-1:0.1.6-c0.noarch
  - nothing provides python-six needed by xcat-inventory-1:0.1.6-c0.noarch
  - nothing provides PyYAML needed by xcat-inventory-1:0.1.6-c0.noarch
  - nothing provides python-psycopg2 needed by xcat-inventory-1:0.1.6-c0.noarch
  - nothing provides python-jinja2 needed by xcat-inventory-1:0.1.6-c0.noarch
  - nothing provides MySQL-python needed by xcat-inventory-1:0.1.6-c0.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

### PR DESCRIPTION
**Pull request by Obihoernchen**
Fixes https://github.com/xcat2/xcat-inventory/issues/221 and keeps RHEL7 compatibility.

Note: This should be changed to python3 very soon for RHEL8. But for now this works fine, too.
I didn't want to change shebang to python3 as this would break RHEL7 support.
We should think about providing two packages: python2 RHEL7 + python3 RHEL8 in the future.

A new release v0.1.7 should be created.

### CODE REVIEW

**Comment by cxhong** [comment]
The current xcat-inventory package supports RHEL7 with python2.   I don't think it's necessary to change shebang from `python` to `python2`
you are right, we need a new release for RHEL8 with python3.  we are working on if possible release one package can support both `python2` and `python3`

**Comment by Obihoernchen** [comment]
It's necessary, otherwise you get:
```
*** ERROR: ambiguous python shebang in /opt/xcat/bin/xcat-inventory: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
```
when building on RHEL8.

**Comment by cxhong** [comment]
@Obihoernchen ,  which rhel version of system did you build the rpm?   If I build on rhel7 system and run on rhel8 system,  it still hit same issue.
```
 Problem: conflicting requests
  - nothing provides python-sqlalchemy >= 0.8.0 needed by xcat-inventory-1:0.1.6-c65.noarch
  - nothing provides python-six needed by xcat-inventory-1:0.1.6-c65.noarch
  - nothing provides PyYAML needed by xcat-inventory-1:0.1.6-c65.noarch
  - nothing provides python-psycopg2 needed by xcat-inventory-1:0.1.6-c65.noarch
  - nothing provides python-jinja2 needed by xcat-inventory-1:0.1.6-c65.noarch
  - nothing provides MySQL-python needed by xcat-inventory-1:0.1.6-c65.noarch
```

**Comment by cxhong** [comment]
I will merge this PR,  and will build two RPM , one for rhel7 and one for rhel8

**Pull request merged**
