### PR TITLE
rinstall RESTful API

### PR DESCRIPTION
**Pull request by robin2008**
This PR is for https://github.ibm.com/xcat2/task_management/issues/136, and below changes included:
- `rinstall` python client to xcatd for `rinstall`
- `mkconsole` python client to xcatd for `makegocons`
- single node provision API with POST `/system/nodes/{node}/_operation`
- multiple nodes provision API with POST `/manager/provision`

### CODE REVIEW

**Comment by robin2008** [comment]
1, run `rinstall <node> osimage` with `/system/nodes/{node}/_operation`
`curl -X POST "http://10.6.27.1:5000/api/v2/system/nodes/mid05tor12cn03/_operation" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{  \"action\": \"rinstall\",  \"action_spec\": {\"osimage\":\"\"}}"`
```
10.0.0.104 - - [10/May/2019 03:46:59] "POST /api/v2/system/nodes/mid05tor12cn03/_operation HTTP/1.1" 400 -
2019-05-10 03:47:08,459 DEBUG node.py:94 action_spec={u'osimage': u''}
2019-05-10 03:47:08,459 DEBUG xcat_client_base.py:106 rinstall: noderange=mid05tor12cn03, boot_state=osimage
2019-05-10 03:47:24,429 DEBUG node.py:103 outputs=['Provision node(s): mid05tor12cn03']
10.0.0.104 - - [10/May/2019 03:47:24] "POST /api/v2/system/nodes/mid05tor12cn03/_operation HTTP/1.1" 200 -
```
And check the CLI
```
lsdef mid05tor12cn03 -i status,statustime
Object name: mid05tor12cn03
    status=installing
    statustime=05-10-2019 03:50:39
```

2, run `rinstall <node> shell` with `/system/nodes/{node}/_operation`
```
curl -X POST "http://10.6.27.1:5000/api/v2/system/nodes/mid05tor12cn03/_operation" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{  \"action\": \"rinstall\",  \"action_spec\": {\"boot_state\":\"shell\"}}"

10.0.0.104 - - [10/May/2019 03:47:24] "POST /api/v2/system/nodes/mid05tor12cn03/_operation HTTP/1.1" 200 -
2019-05-10 03:52:23,826 DEBUG node.py:94 action_spec={u'boot_state': u'shell'}
2019-05-10 03:52:23,826 DEBUG xcat_client_base.py:106 rinstall: noderange=mid05tor12cn03, boot_state=shell
2019-05-10 03:52:48,402 DEBUG node.py:103 outputs=['Provision node(s): mid05tor12cn03']

```

And check the CLI
```
lsdef mid05tor12cn03 -i status,statustime
Object name: mid05tor12cn03
    status=powering-on
    statustime=05-10-2019 03:52:48
```

**Comment by bybai** [comment]
I am ok to merge it.

**Comment by whowutwut** [comment]
@cxhong  @gurevichmark We should take a look at these changes and see if we can compare it... or at least  push the performance testing framework to compare with legacy code.    Seems like with this change we can do something with the new server

**Comment by robin2008** [comment]
@vhu
This is bypass to xcatd, REST -> xcatd -> old plugin.
I don't think there would be better performance, but we care not bad performance is okay when comparing the legacy code.

**Pull request merged**
